# DO NOT EDIT
# This makefile makes sure all linkable targets are
# up-to-date with anything they link to
default:
	echo "Do not invoke directly"

# For each target create a dummy rule so the target does not have to exist


# Rules to remove targets that are older than anything to which they
# link.  This forces Xcode to relink the targets from scratch.  It
# does not seem to check these dependencies itself.
PostBuild.winpr-asn1.Debug:
PostBuild.winpr-bcrypt.Debug:
PostBuild.winpr-com.Debug:
PostBuild.winpr-credentials.Debug:
PostBuild.winpr-credui.Debug:
PostBuild.winpr-crt.Debug:
PostBuild.winpr-crypto.Debug:
PostBuild.winpr-dsparse.Debug:
PostBuild.winpr-environment.Debug:
PostBuild.winpr-error.Debug:
PostBuild.winpr-file.Debug:
PostBuild.winpr-handle.Debug:
PostBuild.winpr-heap.Debug:
PostBuild.winpr-input.Debug:
PostBuild.winpr-interlocked.Debug:
PostBuild.winpr-io.Debug:
PostBuild.winpr-library.Debug:
PostBuild.winpr-nt.Debug:
PostBuild.winpr-path.Debug:
PostBuild.winpr-pipe.Debug:
PostBuild.winpr-pool.Debug:
PostBuild.winpr-registry.Debug:
PostBuild.winpr-rpc.Debug:
PostBuild.winpr-sspi.Debug:
PostBuild.winpr-sspicli.Debug:
PostBuild.winpr-synch.Debug:
PostBuild.winpr-sysinfo.Debug:
PostBuild.winpr-thread.Debug:
PostBuild.winpr-timezone.Debug:
PostBuild.winpr-utils.Debug:
PostBuild.winpr-winhttp.Debug:
PostBuild.winpr-winsock.Debug:
PostBuild.winpr-wtsapi.Debug:
PostBuild.winpr-asn1.Release:
PostBuild.winpr-bcrypt.Release:
PostBuild.winpr-com.Release:
PostBuild.winpr-credentials.Release:
PostBuild.winpr-credui.Release:
PostBuild.winpr-crt.Release:
PostBuild.winpr-crypto.Release:
PostBuild.winpr-dsparse.Release:
PostBuild.winpr-environment.Release:
PostBuild.winpr-error.Release:
PostBuild.winpr-file.Release:
PostBuild.winpr-handle.Release:
PostBuild.winpr-heap.Release:
PostBuild.winpr-input.Release:
PostBuild.winpr-interlocked.Release:
PostBuild.winpr-io.Release:
PostBuild.winpr-library.Release:
PostBuild.winpr-nt.Release:
PostBuild.winpr-path.Release:
PostBuild.winpr-pipe.Release:
PostBuild.winpr-pool.Release:
PostBuild.winpr-registry.Release:
PostBuild.winpr-rpc.Release:
PostBuild.winpr-sspi.Release:
PostBuild.winpr-sspicli.Release:
PostBuild.winpr-synch.Release:
PostBuild.winpr-sysinfo.Release:
PostBuild.winpr-thread.Release:
PostBuild.winpr-timezone.Release:
PostBuild.winpr-utils.Release:
PostBuild.winpr-winhttp.Release:
PostBuild.winpr-winsock.Release:
PostBuild.winpr-wtsapi.Release:
PostBuild.winpr-asn1.MinSizeRel:
PostBuild.winpr-bcrypt.MinSizeRel:
PostBuild.winpr-com.MinSizeRel:
PostBuild.winpr-credentials.MinSizeRel:
PostBuild.winpr-credui.MinSizeRel:
PostBuild.winpr-crt.MinSizeRel:
PostBuild.winpr-crypto.MinSizeRel:
PostBuild.winpr-dsparse.MinSizeRel:
PostBuild.winpr-environment.MinSizeRel:
PostBuild.winpr-error.MinSizeRel:
PostBuild.winpr-file.MinSizeRel:
PostBuild.winpr-handle.MinSizeRel:
PostBuild.winpr-heap.MinSizeRel:
PostBuild.winpr-input.MinSizeRel:
PostBuild.winpr-interlocked.MinSizeRel:
PostBuild.winpr-io.MinSizeRel:
PostBuild.winpr-library.MinSizeRel:
PostBuild.winpr-nt.MinSizeRel:
PostBuild.winpr-path.MinSizeRel:
PostBuild.winpr-pipe.MinSizeRel:
PostBuild.winpr-pool.MinSizeRel:
PostBuild.winpr-registry.MinSizeRel:
PostBuild.winpr-rpc.MinSizeRel:
PostBuild.winpr-sspi.MinSizeRel:
PostBuild.winpr-sspicli.MinSizeRel:
PostBuild.winpr-synch.MinSizeRel:
PostBuild.winpr-sysinfo.MinSizeRel:
PostBuild.winpr-thread.MinSizeRel:
PostBuild.winpr-timezone.MinSizeRel:
PostBuild.winpr-utils.MinSizeRel:
PostBuild.winpr-winhttp.MinSizeRel:
PostBuild.winpr-winsock.MinSizeRel:
PostBuild.winpr-wtsapi.MinSizeRel:
PostBuild.winpr-asn1.RelWithDebInfo:
PostBuild.winpr-bcrypt.RelWithDebInfo:
PostBuild.winpr-com.RelWithDebInfo:
PostBuild.winpr-credentials.RelWithDebInfo:
PostBuild.winpr-credui.RelWithDebInfo:
PostBuild.winpr-crt.RelWithDebInfo:
PostBuild.winpr-crypto.RelWithDebInfo:
PostBuild.winpr-dsparse.RelWithDebInfo:
PostBuild.winpr-environment.RelWithDebInfo:
PostBuild.winpr-error.RelWithDebInfo:
PostBuild.winpr-file.RelWithDebInfo:
PostBuild.winpr-handle.RelWithDebInfo:
PostBuild.winpr-heap.RelWithDebInfo:
PostBuild.winpr-input.RelWithDebInfo:
PostBuild.winpr-interlocked.RelWithDebInfo:
PostBuild.winpr-io.RelWithDebInfo:
PostBuild.winpr-library.RelWithDebInfo:
PostBuild.winpr-nt.RelWithDebInfo:
PostBuild.winpr-path.RelWithDebInfo:
PostBuild.winpr-pipe.RelWithDebInfo:
PostBuild.winpr-pool.RelWithDebInfo:
PostBuild.winpr-registry.RelWithDebInfo:
PostBuild.winpr-rpc.RelWithDebInfo:
PostBuild.winpr-sspi.RelWithDebInfo:
PostBuild.winpr-sspicli.RelWithDebInfo:
PostBuild.winpr-synch.RelWithDebInfo:
PostBuild.winpr-sysinfo.RelWithDebInfo:
PostBuild.winpr-thread.RelWithDebInfo:
PostBuild.winpr-timezone.RelWithDebInfo:
PostBuild.winpr-utils.RelWithDebInfo:
PostBuild.winpr-winhttp.RelWithDebInfo:
PostBuild.winpr-winsock.RelWithDebInfo:
PostBuild.winpr-wtsapi.RelWithDebInfo:
